In [1]:
import torch
from torch import nn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv('credit-a.csv',header=None)

In [3]:
data

0      1       2   3   4   5   6     7   8   9   10  11  12   13     14  \
0     0  30.83   0.000   0   0   9   0  1.25   0   0   1   1   0  202    0.0   
1     1  58.67   4.460   0   0   8   1  3.04   0   0   6   1   0   43  560.0   
2     1  24.50   0.500   0   0   8   1  1.50   0   1   0   1   0  280  824.0   
3     0  27.83   1.540   0   0   9   0  3.75   0   0   5   0   0  100    3.0   
4     0  20.17   5.625   0   0   9   0  1.71   0   1   0   1   2  120    0.0   
..   ..    ...     ...  ..  ..  ..  ..   ...  ..  ..  ..  ..  ..  ...    ...   
648   0  21.08  10.085   1   1  11   1  1.25   1   1   0   1   0  260    0.0   
649   1  22.67   0.750   0   0   0   0  2.00   1   0   2   0   0  200  394.0   
650   1  25.25  13.500   1   1  13   7  2.00   1   0   1   0   0  200    1.0   
651   0  17.92   0.205   0   0  12   0  0.04   1   1   0   1   0  280  750.0   
652   0  35.00   3.375   0   0   0   1  8.29   1   1   0   0   0    0    0.0   

     15  
0    -1  
1    -1  
2    -1  
3    -1  
4    -1  
..   ..  
648   1  
649   1  
650   1  
651   1  
652   1  

[653 rows x 16 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 653 entries, 0 to 652
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       653 non-null    int64  
 1   1       653 non-null    float64
 2   2       653 non-null    float64
 3   3       653 non-null    int64  
 4   4       653 non-null    int64  
 5   5       653 non-null    int64  
 6   6       653 non-null    int64  
 7   7       653 non-null    float64
 8   8       653 non-null    int64  
 9   9       653 non-null    int64  
 10  10      653 non-null    int64  
 11  11      653 non-null    int64  
 12  12      653 non-null    int64  
 13  13      653 non-null    int64  
 14  14      653 non-null    float64
 15  15      653 non-null    int64  
dtypes: float64(4), int64(12)
memory usage: 81.8 KB


In [5]:
X=data.iloc[:,:-1]

In [6]:
X.values

array([[0.000e+00, 3.083e+01, 0.000e+00, ..., 0.000e+00, 2.020e+02,
        0.000e+00],
       [1.000e+00, 5.867e+01, 4.460e+00, ..., 0.000e+00, 4.300e+01,
        5.600e+02],
       [1.000e+00, 2.450e+01, 5.000e-01, ..., 0.000e+00, 2.800e+02,
        8.240e+02],
       ...,
       [1.000e+00, 2.525e+01, 1.350e+01, ..., 0.000e+00, 2.000e+02,
        1.000e+00],
       [0.000e+00, 1.792e+01, 2.050e-01, ..., 0.000e+00, 2.800e+02,
        7.500e+02],
       [0.000e+00, 3.500e+01, 3.375e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00]])

In [7]:
X.values.reshape(-1,15)

array([[0.000e+00, 3.083e+01, 0.000e+00, ..., 0.000e+00, 2.020e+02,
        0.000e+00],
       [1.000e+00, 5.867e+01, 4.460e+00, ..., 0.000e+00, 4.300e+01,
        5.600e+02],
       [1.000e+00, 2.450e+01, 5.000e-01, ..., 0.000e+00, 2.800e+02,
        8.240e+02],
       ...,
       [1.000e+00, 2.525e+01, 1.350e+01, ..., 0.000e+00, 2.000e+02,
        1.000e+00],
       [0.000e+00, 1.792e+01, 2.050e-01, ..., 0.000e+00, 2.800e+02,
        7.500e+02],
       [0.000e+00, 3.500e+01, 3.375e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00]])

In [8]:
Y=data.iloc[:,-1].replace(-1,0)

In [9]:
Y

0      0
1      0
2      0
3      0
4      0
      ..
648    1
649    1
650    1
651    1
652    1
Name: 15, Length: 653, dtype: int64

In [10]:
X=torch.from_numpy(X.values).type(torch.float32)
Y=torch.from_numpy(Y.values.reshape(-1,1)).type(torch.float32)

In [11]:
X.size()

torch.Size([653, 15])

In [12]:
Y.shape

torch.Size([653, 1])

In [13]:
model=nn.Sequential(
            nn.Linear(15,1),
            nn.Sigmoid()
)

In [14]:
model

Sequential(
  (0): Linear(in_features=15, out_features=1, bias=True)
  (1): Sigmoid()
)

In [15]:
loss_fn=nn.BCELoss()

In [16]:
opt=torch.optim.Adam(model.parameters(),lr=0.001)

In [17]:
batches=16
no_of_batches=653//16 #//是整除的意思，训练不能训练小数次

In [18]:
epoches=1000

In [19]:
for epoch in range(epoches):      #一共训练多少遍
    for batch in range(no_of_batches):  #训练一遍需要训练多少个小块
        start=batch * batches
        end=start + batches  #使用start和end这样就每次取出16个出来
        x=X[start:end]
        y=Y[start:end]        #这样就取出来了16个x和16个y
        y_pred=model(x)       #把x输入模型，进行预测
        loss=loss_fn(y_pred,y)#通过损失函数计算损失
        opt.zero_grad() #optim里自带的梯度清零的函数，会将模型中变量的梯度全部置为零
        loss.backward() #反向传播，计算每个变量的梯度
        opt.step()      #利用内置函数，使用设定好的优化方法进行优化

In [21]:
model.state_dict(),model.parameters() #这俩都是模型的参数

(OrderedDict([('0.weight',
               tensor([[-3.0012e-01, -8.9614e-03,  3.5728e-02,  2.6205e-01,  2.8156e-01,
                        -5.8356e-03,  2.0751e-01, -1.5546e-01,  4.4849e+00,  2.9633e-01,
                        -1.4627e-01, -2.8960e-01, -2.2359e-01,  2.0060e-03,  1.1243e-04]])),
              ('0.bias', tensor([-0.4790]))]),
 <generator object Module.parameters at 0x0000019E473AFCF0>)

In [22]:
for i in model.parameters():
    print(i)

Parameter containing:
tensor([[-3.0012e-01, -8.9614e-03,  3.5728e-02,  2.6205e-01,  2.8156e-01,
         -5.8356e-03,  2.0751e-01, -1.5546e-01,  4.4849e+00,  2.9633e-01,
         -1.4627e-01, -2.8960e-01, -2.2359e-01,  2.0060e-03,  1.1243e-04]],
       requires_grad=True)
Parameter containing:
tensor([-0.4790], requires_grad=True)


In [ ]:
((model(X).data.numpy()>0.5).astype('int')==Y.numpy()).mean()

In [ ]:
(model(X).data.numpy()>0.5).astype('int')==Y.numpy()

In [ ]:
data=pd.read_csv('credit-a.csv',header=None)

In [ ]:
X=data.iloc[:,:-1]
Y=data.iloc[:,-1].replace(-1,0)

In [ ]:
X

In [ ]:
X=torch.from_numpy(X.values).type(torch.float32)

In [ ]:
Y=torch.from_numpy(Y.values).type(torch.float32).reshape(-1,1)

In [ ]:
model=nn.Sequential(
    nn.Linear(15,1),
    nn.Sigmoid()
)

In [ ]:
loss_fn=nn.BCELoss()
opt=torch.optim.Adam(model.parameters(),lr=0.0001)

In [ ]:
batches=16
no_of_batches=653//16
epoches=50000

In [ ]:
for epoch in range(epoches):
    for batch in range(batches):
        start=batch*batches
        end=start+batches
        x=X[start:end]
        y=Y[start:end]
        y_pred=model(x)
        opt.zero_grad()
        loss=loss_fn(y_pred,y)
        loss.backward()
        opt.step()

In [ ]:
((model(X).data>0.5)==Y.data).numpy().astype(np.float32).mean()

('torch.FloatTensor', <function Tensor.type>)